/* Original short practice for English/Thai learners. Each question targets one
   intended meaning, not a claim that the distractors never occur in Japanese.
   Stable grammar IDs refer to GRAMMAR in index.html. */
var MASTERY_GROUPS = [];
var MASTERY_EXERCISES = [];
var MASTERY_FORM_GUIDE = [];
var MASTERY_SOURCES = [
  {title:'Japan Foundation: とたん and や否や',url:'https://www.jpf.go.jp/j/project/japanese/teach/tsushin/grammar/200906.html'},
  {title:'Japan Foundation: うちに / ないうちに',url:'https://www.kyozai.jpf.go.jp/kyozai/material/BMA00065/ja/render.do'},
  {title:'Tokyo University of Foreign Studies: conditionals',url:'https://www.coelang.tufs.ac.jp/mt/ja/gmod/contents/explanation/083.html'},
  {title:'Japan Foundation: uses of こと',url:'https://www.jpf.go.jp/j/project/japanese/teach/tsushin/grammar/201203.html'},
  {title:'MLC Japanese School: わけにはいかない',url:'https://www.mlcjapanese.co.jp/img/wakeniwaikanai_n3_answer.pdf'},
  {title:'MLC Japanese School: わけだ / というわけだ',url:'https://www.mlcjapanese.co.jp/n3_014.html'},
  {title:'Japanese teacher Tanosuke: ようものなら',url:'https://tanosuke.com/youmononara'}
];
(function(){
  function member(id, cue_en, cue_th, before_en, before_th, after_en, after_th) {
    return {id:id,cue_en:cue_en,cue_th:cue_th,before_en:before_en,before_th:before_th,after_en:after_en,after_th:after_th};
  }
  function group(id,title,th,rule_en,rule_th,members){
    MASTERY_GROUPS.push({id:id,title:title,th:th,rule_en:rule_en,rule_th:rule_th,ids:members.map(function(m){return m.id;}),members:members});
  }
  group('time','Right after, during, or only after?','ทันที ระหว่าง หรือหลังจากทำแล้วถึงเข้าใจ',
    'Read what happens next: a surprise, a planned action, an interruption, or a discovery?',
    'ดูสิ่งที่ตามมา: เรื่องไม่คาดคิด แผนที่จะทำ เหตุการณ์แทรก หรือเพิ่งเข้าใจ?',[
    member('n3a05','とたん: a sudden event immediately after an action.','とたん: เกิดเรื่องฉับพลันทันทีหลังทำสิ่งหนึ่ง','past verb: 開けた','กริยารูปอดีต: 開けた','A sudden event; not your promise or request.','เหตุการณ์ฉับพลัน ไม่ใช่คำสัญญาหรือคำขอของผู้พูด'),
    member('n2a03','次第: do the next planned action as soon as ready.','次第: พอพร้อมแล้วจะทำขั้นต่อไปทันที','masu stem: 終わり','ตัด ます: 終わり','A plan, request, or procedure.','แผน คำขอ หรือขั้นตอน'),
    member('n3a06','最中に: something occurs in the middle of an activity.','最中に: เกิดบางอย่างระหว่างที่กำลังทำอยู่','Vている / noun + の','Vている / คำนาม + の','An event during that activity, often an interruption.','เหตุการณ์ระหว่างกิจกรรมนั้น มักเป็นสิ่งที่เข้ามาขัดจังหวะ'),
    member('n3a08','てはじめて: only after the experience did something become possible or clear.','てはじめて: ต้องผ่านประสบการณ์นั้นก่อนจึงทำได้หรือเข้าใจ','te form: 経験して','รูป て: 経験して','A new realization or ability.','ความเข้าใจหรือความสามารถที่เพิ่งเกิดขึ้น')
  ]);
  group('window','A window of time or “just happened”?','ช่วงเวลาที่ยังมีโอกาส หรือเพิ่งเกิดขึ้น',
    'うちに highlights a changing opportunity. 間 gives a time span. ところ and ばかり describe timing from different viewpoints.',
    'うちに เน้นโอกาสที่อาจหมดไป ส่วน 間 บอกช่วงเวลา และ ところ กับ ばかり มองความใกล้ของเวลาต่างกัน',[
    member('n3a03','うちに: act before a state changes; also gradual change during an activity.','うちに: ทำก่อนสภาพเปลี่ยน หรือเกิดการเปลี่ยนแปลงระหว่างทำ','Vる / Vている / Vない / i-adj / na-adj + な / noun + の','Vる / Vている / Vない / คุณศัพท์ い / คุณศัพท์ な + な / นาม + の','Use the opportunity, or describe a change over time.','ใช้โอกาสนั้น หรือบอกการเปลี่ยนแปลงที่ค่อย ๆ เกิด'),
    member('n3a04','間: throughout a span; 間に: an event within it.','間: ตลอดช่วงนั้น / 間に: เหตุการณ์หนึ่งภายในช่วงนั้น','Vている / noun + の (common patterns)','Vている / คำนาม + の (รูปที่พบบ่อย)','間 often pairs with a continuous action; 間に with an occurrence.','間 มักตามด้วยการกระทำต่อเนื่อง / 間に ตามด้วยเหตุการณ์ที่เกิดขึ้น'),
    member('n3a01','ところ: the exact stage—before, during, or just after the action.','ところ: บอกขั้นของการกระทำ ก่อนทำ ระหว่างทำ หรือเพิ่งเสร็จ','Dictionary form / ている / た + ところ','รูปพจนานุกรม / ている / た + ところ','The verb form tells you which stage.','รูปกริยาบอกว่าอยู่ขั้นไหน'),
    member('n3a02','たばかり: the speaker considers it recent, even if some time passed.','たばかり: ผู้พูดรู้สึกว่าเพิ่งทำ แม้เวลาจะผ่านไปแล้ว','past verb + ばかり','กริยารูปอดีต + ばかり','A comment based on how recent it feels.','ความเห็นที่อิงกับความรู้สึกว่าเพิ่งเกิด')
  ]);
  group('obligation','Cannot do vs cannot avoid doing','ทำไม่ได้เพราะหน้าที่ หรือจำเป็นต้องทำ',
    'Watch the negative BEFORE わけ: 行くわけにはいかない = cannot go; 行かないわけにはいかない = must go.',
    'ดูคำปฏิเสธหน้า わけ: 行くわけにはいかない = ไปไม่ได้ / 行かないわけにはいかない = จำเป็นต้องไป',[
    member('n3c06','Vるわけにはいかない: circumstances or responsibility stop me.','Vるわけにはいかない: หน้าที่หรือสถานการณ์ทำให้ทำไม่ได้','dictionary verb: 休む','กริยารูปพจนานุกรม: 休む','A reason why doing it would be unacceptable.','เหตุผลว่าทำแบบนั้นไม่ได้หรือไม่เหมาะสม'),
    member('n2c14','Vないわけにはいかない: I have an obligation to do it.','Vないわけにはいかない: มีหน้าที่จึงไม่ทำไม่ได้','negative verb: 休まない','กริยารูปปฏิเสธ: 休まない','The action must happen.','จำเป็นต้องทำกริยานั้น'),
    member('n2c13','ざるを得ない: no realistic alternative, often reluctantly.','ざるを得ない: ไม่มีทางเลือกอื่น มักทำอย่างไม่เต็มใจ','negative stem + ざる; する → せざる','ตัด ない แล้วเติม ざる; する → せざる','A forced decision or unavoidable response.','การตัดสินใจที่จำเป็นหรือหลีกเลี่ยงไม่ได้'),
    member('n2c22','ことはない: there is no need to do it.','ことはない: ไม่จำเป็นต้องทำ','dictionary verb: 急ぐ','กริยารูปพจนานุกรม: 急ぐ','Reassurance or advice that it is unnecessary.','ปลอบใจหรือบอกว่าไม่ต้องทำก็ได้')
  ]);
  group('wake','The わけ family: logic, not one meaning','กลุ่ม わけ: ดูตรรกะของประโยค',
    '“No way”, “not necessarily”, and “that explains it” are different messages. Learn the whole ending.',
    '“เป็นไปไม่ได้” “ไม่ได้หมายความว่า...” และ “มิน่าล่ะ” สื่อคนละอย่าง จำส่วนท้ายทั้งชุด',[
    member('n2d17','わけがない: reject the possibility strongly.','わけがない: ยืนยันหนักแน่นว่าเป็นไปไม่ได้','plain verb / i-adj; na-adj + な; noun + な・である (の also occurs)','กริยาธรรมดา / คุณศัพท์ い; คุณศัพท์ な + な; นาม + な・である (พบ の ได้เช่นกัน)','An emphatic denial of possibility.','ปฏิเสธความเป็นไปได้อย่างหนักแน่น'),
    member('n3b09','わけではない: correct a conclusion or overgeneralization.','わけではない: แก้ความเข้าใจหรือการเหมารวม','plain verb / i-adj; na-adj + な; noun + な・である (の also occurs)','กริยาธรรมดา / คุณศัพท์ い; คุณศัพท์ な + な; นาม + な・である (พบ の ได้เช่นกัน)','Often: some cases differ, or the real reason is different.','มักบอกว่าบางกรณีต่างออกไป หรือเหตุผลจริงไม่ใช่อย่างนั้น'),
    member('n3b08','わけだ: a fact explains a conclusion.','わけだ: ข้อมูลหนึ่งทำให้เข้าใจข้อสรุป','plain verb / i-adj; na-adj + な; noun + な・である (の also occurs)','กริยาธรรมดา / คุณศัพท์ い; คุณศัพท์ な + な; นาม + な・である (พบ の ได้เช่นกัน)','“So that is why”; a logical consequence.','“อย่างนี้นี่เอง” หรือผลที่ตามมาตามเหตุผล'),
    member('n2c28','とは限らない: it is not true in every case.','とは限らない: ไม่เป็นเช่นนั้นเสมอไป','plain clause, including noun/na-adj + だ','อนุประโยครูปธรรมดา รวมถึง นาม/คุณศัพท์ な + だ','A qualification of a general claim.','จำกัดขอบเขตข้อความที่เหมารวม')
  ]);
  group('evidence','I heard it vs it looks that way','ได้ยินมา หรือดูจากสิ่งตรงหน้า',
    'The shape before そう changes its meaning. 降るそうだ = reported; 降りそうだ = looks likely.',
    'รูปหน้า そう เปลี่ยนความหมาย: 降るそうだ = ได้ยินว่าจะตก / 降りそうだ = ดูท่าจะตก',[
    member('n3b01','そうだ (report): pass on information from a source.','そうだ (บอกต่อ): ถ่ายทอดข้อมูลที่ได้ยินหรืออ่าน','plain sentence: おいしい / 元気だ / 降る','ประโยครูปธรรมดา: おいしい / 元気だ / 降る','A report; identify the source when useful.','บอกข้อมูลจากแหล่งอื่น'),
    member('n3b02','そうだ (appearance): an impression or an impending event.','そうだ (ลักษณะที่เห็น): ดูท่าเป็นเช่นนั้นหรือใกล้เกิด','masu stem / i-adj without い / na-adj stem','ตัด ます / ตัด い ของคุณศัพท์ い / รากคุณศัพท์ な','Your impression, rather than reported wording.','ความรู้สึกจากสิ่งที่สังเกต'),
    member('n3b03','ようだ: infer from clues; nouns take の and na-adjectives take な.','ようだ: อนุมานจากหลักฐาน นามใช้ の และคุณศัพท์ な ใช้ な','plain verb / i-adj / na-adj + な / noun + の','กริยาธรรมดา / คุณศัพท์ い / คุณศัพท์ な + な / นาม + の','An inference supported by signs.','ข้อสันนิษฐานที่มีสิ่งบ่งชี้'),
    member('n3b06','にちがいない: the speaker is very confident.','にちがいない: ผู้พูดมั่นใจมาก','plain verb / i-adj / noun or na-adj stem','กริยาธรรมดา / คุณศัพท์ い / นามหรือรากคุณศัพท์ な','A strong inference; it is still the speaker’s judgment.','ข้อสันนิษฐานที่มั่นใจสูง แต่ยังเป็นความเห็นผู้พูด')
  ]);
  group('condition','If: order and intention matter','ถ้า: ดูลำดับเวลาและความตั้งใจ',
    'たら can put a request after completion. なら responds to a premise, even before that event. と commonly gives a regular result.',
    'たら ใช้ขอให้ทำหลังเหตุการณ์จบได้ / なら รับเงื่อนไขที่พูดถึง แม้ให้ทำก่อน / と มักบอกผลที่เกิดตามปกติ',[
    member('n3a21','たら: if/when A is completed, then B; requests are possible.','たら: ถ้า/เมื่อ A เสร็จแล้วจึง B ใช้กับคำขอได้','past form + ら: 着いたら','รูปอดีต + ら: 着いたら','An event, intention, or request after the condition.','เหตุการณ์ ความตั้งใจ หรือคำขอหลังเงื่อนไข'),
    member('n3a22','なら: given that plan or topic, here is my response.','なら: ถ้าเป็นเรื่องหรือแผนนั้น ก็ขอเสนอว่า...','plain clause; noun/na-adj without だ','อนุประโยครูปธรรมดา; นาม/คุณศัพท์ な ไม่เติม だ','Advice can apply before the mentioned action.','คำแนะนำอาจให้ทำก่อนเหตุการณ์ที่พูดถึง'),
    member('n3a23','と: a regular, automatic result; also discoveries in narratives.','と: ผลปกติหรืออัตโนมัติ และใช้เล่าการค้นพบได้','nonpast plain clause; noun/na-adj + だ','อนุประโยครูปธรรมดาไม่ใช่อดีต; นาม/คุณศัพท์ な + だ','For the regular-result use, not a one-time request.','ถ้าใช้บอกผลปกติ ส่วนหลังไม่ใช่คำขอเฉพาะครั้ง'),
    member('n2b02','ないことには: without first doing A, B cannot happen.','ないことには: ถ้าไม่ทำ A ก่อน ก็ทำ B ไม่ได้','negative verb: 調べない','กริยาปฏิเสธ: 調べない','A negative result or inability.','ผลปฏิเสธหรือสิ่งที่ยังทำไม่ได้'),
    member('n2b03','ものなら: if an unlikely ability were possible, I would…','ものなら: ถ้าทำสิ่งที่ยากจะเป็นไปได้ได้จริง ก็อยาก...','often a potential verb: 戻れる','มักเป็นรูปสามารถ: 戻れる','A wish based on an unlikely possibility.','ความปรารถนาที่อาศัยเงื่อนไขซึ่งเป็นไปได้ยาก'),
    member('n2g11','ようものなら: if someone were to do that, trouble would follow.','ようものなら: ถ้าขืนทำอย่างนั้น จะเกิดเรื่องตามมา','volitional verb: 言おう / しよう','รูปชักชวน/ตั้งใจ: 言おう / しよう','An undesirable consequence.','ผลที่ไม่พึงประสงค์')
  ]);
  group('cause','Thanks, blame, excuse, or regret?','ขอบคุณ โทษ แก้ตัว หรือเสียดาย',
    'Choose the speaker’s attitude as well as “because”. Context can reverse the usual positive/negative reading, especially sarcasm.',
    'เลือกตามท่าทีผู้พูดด้วย ไม่ใช่ดูแค่ “เพราะ” บางบริบทกลับน้ำเสียงได้ โดยเฉพาะการประชด',[
    member('n3a14','おかげで: credit a helpful cause (usually gratitude).','おかげで: ยกความดีให้สาเหตุที่ช่วย มักรู้สึกขอบคุณ','plain verb / i-adj / na-adj + な / noun + の','กริยาธรรมดา / คุณศัพท์ い / คุณศัพท์ な + な / นาม + の','Usually a welcome result; sarcasm is possible.','มักตามด้วยผลดี แต่ใช้ประชดได้'),
    member('n3a13','せいで: blame a cause for an unwelcome result.','せいで: โทษสาเหตุที่ทำให้เกิดผลไม่ดี','plain verb / i-adj / na-adj + な / noun + の','กริยาธรรมดา / คุณศัพท์ い / คุณศัพท์ な + な / นาม + の','Usually an unwanted result.','มักตามด้วยผลที่ไม่ต้องการ'),
    member('n3a16','もので: explain a personal reason, often as an excuse.','もので: อธิบายเหตุผลส่วนตัว มักเป็นคำแก้ตัว','plain verb / i-adj / na-adj + な / noun + な','กริยาธรรมดา / คุณศัพท์ い / คุณศัพท์ な + な / นาม + な','An explanation of why something happened.','คำอธิบายว่าเหตุใดจึงเกิดเรื่องนั้น'),
    member('n2a14','ばかりに: regret that this one cause led to a bad result.','ばかりに: เสียดายที่เพียงเหตุนี้ทำให้เกิดผลร้าย','plain verb / i-adj / na-adj + な / noun + である','กริยาธรรมดา / คุณศัพท์ い / คุณศัพท์ な + な / นาม + である','An unfortunate consequence; not just any reason.','ผลเสียที่รู้สึกเสียดาย ไม่ใช่เหตุผลทั่วไป')
  ]);
  group('contrast','Although vs far from it','แม้ว่า หรือห่างไกลจากที่คิด',
    'ものの admits A but adds a problem. どころか overturns an expectation. どころではない says circumstances do not allow it.',
    'ものの ยอมรับ A แล้วบอกปัญหา / どころか หักความคาดหมาย / どころではない สถานการณ์ไม่อำนวยให้ทำ',[
    member('n2a20','ものの: A is true, but the expected result has not followed.','ものの: A จริง แต่ผลที่คาดยังไม่เกิด','plain verb / i-adj / na-adj + な / noun + である','กริยาธรรมดา / คุณศัพท์ い / คุณศัพท์ な + な / นาม + である','A contrasting fact or unsolved issue.','ข้อเท็จจริงที่ขัดกันหรือปัญหาที่ยังค้าง'),
    member('n2a24','どころか: far from A; actually the opposite or even more.','どころか: ไม่ใช่แค่ A แต่ตรงข้ามหรือยิ่งกว่านั้น','plain verb / i-adj / noun / na-adj + な','กริยาธรรมดา / คุณศัพท์ い / นาม / คุณศัพท์ な + な','A stronger or contrary reality.','ข้อเท็จจริงที่ตรงข้ามหรือเกินความคาดหมาย'),
    member('n2c27','どころではない: I am in no situation to do that.','どころではない: สถานการณ์แบบนี้ทำสิ่งนั้นไม่ไหว','dictionary verb / noun','กริยารูปพจนานุกรม / นาม','A reason such as urgent work, illness, or worry.','เหตุเช่นงานด่วน ความเจ็บป่วย หรือความกังวล'),
    member('n2a25','からといって: just because A, do not conclude B.','からといって: อย่าสรุป B เพียงเพราะ A','plain clause; noun/na-adj + だ','อนุประโยครูปธรรมดา; นาม/คุณศัพท์ な + だ','Usually rejects an inference, often with わけではない or とは限らない.','มักปฏิเสธข้อสรุปด้วย わけではない หรือ とは限らない')
  ]);
  group('mono_koto','もの and こと: read the ending','もの กับ こと: ดูทั้งส่วนท้าย',
    'Do not memorize one English meaning for もの or こと. Tense and the complete pattern decide the job.',
    'อย่าจำว่า もの หรือ こと แปลคำเดียว รูปกริยาและสำนวนทั้งชุดเป็นตัวกำหนดความหมาย',[
    member('n3c25','ものだ: often describes a general tendency or a feeling.','ものだ: มักบอกธรรมชาติทั่วไปหรือความรู้สึก','plain verb / i-adj / na-adj + な','กริยาธรรมดา / คุณศัพท์ い / คุณศัพท์ な + な','A general observation, with other readings in context.','ข้อสังเกตทั่วไป โดยอาจมีความหมายอื่นตามบริบท'),
    member('n2d16','たものだ: remember what used to happen, often fondly.','たものだ: นึกย้อนถึงสิ่งที่เคยทำเป็นประจำ','past verb: 遊んだ','กริยารูปอดีต: 遊んだ','A recollection; a repeated past habit is a common use.','การรำลึก มักเป็นกิจวัตรในอดีต'),
    member('n2c21','ことだ: practical advice about what to do or avoid.','ことだ: แนะนำว่าควรทำหรือเลี่ยงอะไร','dictionary / negative verb: 読む・読まない','กริยารูปพจนานุกรม / ปฏิเสธ: 読む・読まない','Advice, commonly from someone guiding the listener.','คำแนะนำ มักจากผู้ที่กำลังชี้แนะแนวทาง'),
    member('n2c22','ことはない: doing it is unnecessary.','ことはない: ไม่จำเป็นต้องทำ','dictionary verb: 心配する','กริยารูปพจนานุกรม: 心配する','Reassurance or a judgment of no necessity.','การปลอบใจหรือบอกว่าไม่จำเป็น'),
    member('n2f10','ものではない: a general warning about improper behavior.','ものではない: เตือนตามหลักทั่วไปว่าไม่ควรทำ','dictionary verb: 笑う','กริยารูปพจนานุกรม: 笑う','A social or moral judgment, stronger than no necessity.','ข้อห้ามเชิงมารยาทหรือหลักการ ไม่ใช่แค่ไม่จำเป็น')
  ]);
  group('change','A change happening vs my deliberate habit','สิ่งที่เปลี่ยนไป กับสิ่งที่ตั้งใจฝึก',
    'Ask who controls it: a process is progressing, an ability has changed, or I intentionally keep doing something.',
    'ดูว่าใครควบคุม: กระบวนการกำลังเปลี่ยน ความสามารถเปลี่ยนไป หรือฉันตั้งใจทำให้เป็นนิสัย',[
    member('n2c07','つつある: a change is currently progressing.','つつある: การเปลี่ยนแปลงกำลังดำเนินอยู่','masu stem: 増え','ตัด ます: 増え','A gradual process, common in explanatory writing.','กระบวนการเปลี่ยนแปลง มักใช้ในภาษาเขียนอธิบาย'),
    member('n2c08','一方だ: a continuing trend in one direction, good or bad.','一方だ: แนวโน้มไปทางเดียวต่อเนื่อง เป็นผลดีหรือร้ายก็ได้','dictionary change verb: 増える','กริยาเปลี่ยนแปลงรูปพจนานุกรม: 増える','A continuing tendency; not inherently negative.','แนวโน้มต่อเนื่อง ไม่จำเป็นต้องเป็นเรื่องลบ'),
    member('n3b11','ようになる: a new ability, habit, or state has developed.','ようになる: ความสามารถ นิสัย หรือสภาพใหม่เกิดขึ้น','dictionary / potential / negative verb','กริยารูปพจนานุกรม / สามารถ / ปฏิเสธ','A change compared with before.','การเปลี่ยนแปลงเมื่อเทียบกับก่อนหน้า'),
    member('n3b12','ようにする: make a conscious effort to do or avoid it.','ようにする: ตั้งใจพยายามทำหรือเลี่ยงสิ่งนั้น','dictionary / negative verb','กริยารูปพจนานุกรม / ปฏิเสธ','An intentional practice; ようにしている for an ongoing effort.','การฝึกโดยตั้งใจ ใช้ ようにしている เมื่อทำต่อเนื่อง')
  ]);
  group('attachment','Build the left side first','ต่อรูปข้างหน้าให้ถูกก่อน',
    'The same word can need different endings before different grammar. Build the required form, then attach the pattern.',
    'คำเดียวกันอาจต้องเปลี่ยนรูปต่างกันตามไวยากรณ์ ทำรูปที่ต้องใช้ให้เสร็จก่อนแล้วค่อยต่อสำนวน',[
    member('n3a09','まま: the state is left unchanged.','まま: คงสภาพเดิมไว้','past / negative verb; na-adj + な; noun + の','กริยาอดีต / ปฏิเสธ; คุณศัพท์ な + な; นาม + の','An action while the earlier state remains.','ทำอีกสิ่งโดยสภาพก่อนหน้ายังไม่เปลี่ยน'),
    member('n3a11','たびに: every occurrence, not just once.','たびに: ทุกครั้งที่เกิดเหตุการณ์นั้น','dictionary verb / noun + の','กริยารูปพจนานุกรม / คำนาม + の','A result that recurs each time.','ผลที่เกิดซ้ำทุกครั้ง'),
    member('n3a26','場合は: if that case arises; useful for instructions.','場合は: หากเกิดกรณีนั้น มักใช้ในคำแนะนำ','plain verb / i-adj / na-adj + な / noun + の','กริยาธรรมดา / คุณศัพท์ い / คุณศัพท์ な + な / นาม + の','What applies in that situation.','สิ่งที่ให้ทำหรือเป็นจริงในกรณีนั้น'),
    member('n2b11','上に: add another point in the same direction.','上に: เพิ่มอีกข้อที่เป็นไปในทิศทางเดียวกัน','plain verb / i-adj / na-adj + な / noun + の・である','กริยาธรรมดา / คุณศัพท์ い / คุณศัพท์ な + な / นาม + の・である','Another benefit, or another drawback.','ข้อดีอีกข้อ หรือข้อเสียอีกข้อ')
  ]);
  group('limits','As long as, as far as, and not limited to','ตราบใด เท่าที่ทราบ และไม่จำกัดแค่',
    '限り is a family. Identify what is limited: a condition, your evidence, or the range of people/things.',
    '限り มีหลายสำนวน ดูว่าจำกัดอะไร: เงื่อนไข หลักฐานที่มี หรือขอบเขตคนและสิ่งของ',[
    member('n2e14','限り: as long as a condition remains true.','限り: ตราบใดที่เงื่อนไขนั้นยังเป็นจริง','dictionary / Vている; negative verb for ない限り','กริยาพจนานุกรม / Vている; ใช้รูปปฏิเสธกับ ない限り','What stays true under that condition.','สิ่งที่ยังเป็นจริงภายใต้เงื่อนไขนั้น'),
    member('n2g14','限りでは: within what I know, saw, or checked.','限りでは: เท่าที่ฉันรู้ เห็น หรือตรวจสอบ','knowledge/evidence verb: 知っている / 調べた','กริยาความรู้หรือหลักฐาน: 知っている / 調べた','A claim limited by that evidence.','ข้อสรุปที่จำกัดตามข้อมูลที่มี'),
    member('n2b18','に限らず: not only this group; others too.','に限らず: ไม่จำกัดแค่กลุ่มนี้ กลุ่มอื่นก็ด้วย','noun','คำนาม','A wider range, often も.','ขอบเขตที่กว้างขึ้น มักมี も'),
    member('n2b17','に限って: precisely this occasion; also disbelief about a particular person.','に限って: ดันเป็นครั้งนี้พอดี หรือเชื่อว่าคนนี้ไม่มีทางทำ','noun','คำนาม','Often an inconvenient coincidence, or a strong personal belief.','มักเป็นเรื่องบังเอิญที่ไม่อยากให้เกิด หรือความเชื่อเกี่ยวกับคนหนึ่ง')
  ]);

  MASTERY_FORM_GUIDE = [
    {id:'dictionary',title:'Dictionary form · Vる',th:'รูปพจนานุกรม · Vる',rule_en:'The form found in a dictionary. Vる is shorthand for dictionary form, even when the verb does not end in る.',rule_th:'รูปที่ใช้ค้นในพจนานุกรม Vる เป็นชื่อย่อของรูปนี้ แม้กริยาบางคำไม่ได้ลงท้ายด้วย る',examples:[{from:'書きます',to:'書く',en:'write → 書くたびに',th:'เขียน → ทุกครั้งที่เขียน'},{from:'食べます',to:'食べる',en:'eat → 食べることにする',th:'กิน → ตัดสินใจว่าจะกิน'},{from:'します',to:'する',en:'do → するしかない',th:'ทำ → ไม่มีทางเลือกนอกจากทำ'}],trap_en:'Do not remove ます and assume you have dictionary form: 書き is a stem; 書く is dictionary form.',trap_th:'ตัด ます อย่างเดียวไม่ได้รูปพจนานุกรม: 書き เป็นราก ส่วน 書く เป็นรูปพจนานุกรม'},
    {id:'stem',title:'Masu stem · Vます without ます',th:'รากรูป ます · ตัด ます ออก',rule_en:'Start with the polite form, then remove ます. This stem joins 次第, つつある, and many compound verbs.',rule_th:'เริ่มจากรูปสุภาพแล้วตัด ます รากนี้ใช้ต่อ 次第, つつある และกริยาประสมหลายแบบ',examples:[{from:'書きます',to:'書き',en:'書き終わる = finish writing',th:'書き終わる = เขียนเสร็จ'},{from:'食べます',to:'食べ',en:'食べすぎる = eat too much',th:'食べすぎる = กินมากเกินไป'},{from:'します',to:'し',en:'回復しつつある = be recovering',th:'回復しつつある = กำลังฟื้นตัว'}],trap_en:'Vます in a connection rule often means the stem, not the full polite ending. 終わり次第, not 終わります次第.',trap_th:'Vます ในสูตรเชื่อมมักหมายถึงราก ไม่ใช่รูปสุภาพเต็ม ใช้ 終わり次第 ไม่ใช่ 終わります次第'},
    {id:'negative',title:'Negative form · Vない',th:'รูปปฏิเสธ · Vない',rule_en:'Group 1 changes the final u-sound to a-sound + ない (う → わない). Group 2 drops る + ない. Learn the irregular verbs separately.',rule_th:'กลุ่ม 1 เปลี่ยนเสียงท้าย u เป็น a แล้วเติม ない (う → わない) กลุ่ม 2 ตัด る แล้วเติม ない ส่วนกริยาพิเศษต้องจำ',examples:[{from:'書く / 買う',to:'書かない / 買わない',en:'not write / not buy',th:'ไม่เขียน / ไม่ซื้อ'},{from:'食べる / する / 来る',to:'食べない / しない / 来ない（こない）',en:'not eat / not do / not come',th:'ไม่กิน / ไม่ทำ / ไม่มา'},{from:'ある',to:'ない',en:'not exist; not あらない',th:'ไม่มี ไม่ใช่ あらない'}],trap_en:'Some patterns keep ない, others replace it: 行かないうちに, but 行かざるを得ない. する → せざるを得ない.',trap_th:'บางสำนวนเก็บ ない บางสำนวนแทนที่: 行かないうちに แต่ 行かざるを得ない / する ใช้ せざるを得ない'},
    {id:'past_te',title:'Past and te forms · Vた / Vて',th:'รูปอดีตและรูป て · Vた / Vて',rule_en:'These forms share sound changes. Group 2: drop る + た/て. For group 1, learn the ending families rather than adding た to dictionary form.',rule_th:'สองรูปนี้เปลี่ยนเสียงแบบเดียวกัน กลุ่ม 2 ตัด る แล้วเติม た/て กลุ่ม 1 ให้จำตามกลุ่มตัวท้าย อย่าเติม た หลังรูปพจนานุกรมตรง ๆ',examples:[{from:'う・つ・る: 買う / 待つ / 帰る',to:'買った・買って / 待った・待って / 帰った・帰って',en:'group 1: った / って',th:'กลุ่ม 1 เปลี่ยนเป็น った / って'},{from:'む・ぶ・ぬ: 読む / 遊ぶ / 死ぬ',to:'読んだ・読んで / 遊んだ・遊んで / 死んだ・死んで',en:'んだ / んで',th:'เปลี่ยนเป็น んだ / んで'},{from:'書く / 泳ぐ / 話す',to:'書いた・書いて / 泳いだ・泳いで / 話した・話して',en:'いた/いて, いだ/いで, した/して',th:'เปลี่ยนเป็น いた/いて, いだ/いで, した/して'},{from:'行く / 食べる / する / 来る',to:'行った・行って / 食べた・食べて / した・して / 来た・来て（きた・きて）',en:'行く is an exception; do not say 行いた.',th:'行く เป็นข้อยกเว้น ไม่ใช้ 行いた'}],trap_en:'A る-ending alone does not identify the group: 帰る is group 1; 食べる is group 2.',trap_th:'เห็นท้าย る ยังบอกกลุ่มไม่ได้: 帰る เป็นกลุ่ม 1 แต่ 食べる เป็นกลุ่ม 2'},
    {id:'adjectives',title:'Nouns, な adjectives, and い adjectives',th:'คำนาม คุณศัพท์ な และคุณศัพท์ い',rule_en:'Attachment belongs to each pattern. Before うちに: 静かな, 学生の, 暖かい. Before もので: 静かな, 学生な, 暖かい.',rule_th:'ต้องดูสูตรของแต่ละสำนวน หน้า うちに ใช้ 静かな, 学生の, 暖かい แต่หน้า もので ใช้ 静かな, 学生な, 暖かい',examples:[{from:'静か + うちに',to:'静かなうちに',en:'while it is quiet',th:'ขณะที่ยังเงียบ'},{from:'学生 + うちに',to:'学生のうちに',en:'while still a student',th:'ขณะที่ยังเป็นนักเรียน/นักศึกษา'},{from:'新人 + もので',to:'新人なもので',en:'because I am new (an explanation)',th:'เพราะเป็นคนใหม่ (อธิบายเหตุผล)'},{from:'忙しい + うちに',to:'忙しいうちに',en:'while busy; retain い',th:'ขณะที่ยุ่ง เก็บ い ไว้'}],trap_en:'Do not use の for every noun or な for every adjective. きれい is a な adjective despite ending in い.',trap_th:'อย่าใส่ の หลังนามทุกครั้ง หรือ な หลังคุณศัพท์ทุกคำ きれい เป็นคุณศัพท์ な แม้ลงท้าย い'},
    {id:'plain',title:'Plain form is a family, not one tense',th:'รูปธรรมดามีหลายกาลและมีปฏิเสธด้วย',rule_en:'Plain includes present/future, past, affirmative, and negative. A rule asking for a plain clause does not automatically mean dictionary form.',rule_th:'รูปธรรมดารวมปัจจุบัน/อนาคต อดีต บอกเล่า และปฏิเสธ สูตรที่ขอรูปธรรมดาไม่ได้หมายถึงรูปพจนานุกรมเสมอ',examples:[{from:'読みます / 読みません',to:'読む / 読まない',en:'nonpast affirmative / negative',th:'ไม่ใช่อดีต แบบบอกเล่า / ปฏิเสธ'},{from:'読みました / 読みませんでした',to:'読んだ / 読まなかった',en:'past affirmative / negative',th:'อดีตแบบบอกเล่า / ปฏิเสธ'},{from:'学生です / 静かです',to:'学生だ / 静かだ',en:'full plain predicates; both keep だ before reportative そうだ',th:'ภาคแสดงธรรมดา เก็บ だ เมื่ออยู่หน้า そうだ ที่ใช้บอกต่อ'}],trap_en:'Then apply the specific connector: 学生だそうだ (reported), but 学生のうちに (while a student).',trap_th:'จากนั้นดูสำนวนที่ต่อ: 学生だそうだ (ได้ยินว่าเป็นนักเรียน) แต่ 学生のうちに (ขณะยังเป็นนักเรียน)'},
    {id:'potential_volitional',title:'Can do vs let’s do · potential / volitional',th:'ทำได้ กับตั้งใจจะทำ · รูปสามารถ / รูปชักชวน',rule_en:'Potential describes ability; volitional expresses intention. Before ものなら, this difference can change a distant wish into a warning.',rule_th:'รูปสามารถบอกว่าทำได้ ส่วนรูปชักชวนบอกความตั้งใจ เมื่อต่อ ものなら ความต่างนี้อาจเปลี่ยนจากความหวังที่ยากเป็นจริงเป็นคำเตือน',examples:[{from:'書く',to:'書ける / 書こう',en:'can write / let’s write',th:'เขียนได้ / มาเขียนกันเถอะ'},{from:'食べる',to:'食べられる / 食べよう',en:'can eat / let’s eat',th:'กินได้ / มากินกันเถอะ'},{from:'する / 来る',to:'できる・しよう / 来られる・来よう（こられる・こよう）',en:'can do / let’s do; can come / let’s come',th:'ทำได้ / มาทำกัน; มาได้ / มากันเถอะ'}],trap_en:'戻れるものなら = if I could return; 戻ろうものなら = if I were to return (with a bad consequence).',trap_th:'戻れるものなら = ถ้ากลับไปได้ / 戻ろうものなら = ถ้าขืนกลับไป (จะเกิดผลร้าย)'}
  ];

  function exercise(id,gid,group,kind,prompt_en,prompt_th,ja,kana,answer,wrong1,wrong2,why_en,why_th,en,th,hint_en,hint_th){
    MASTERY_EXERCISES.push({id:id,gid:gid,group:group,kind:kind,prompt_en:prompt_en,prompt_th:prompt_th,ja:ja,kana:kana,answer:answer,options:[answer,wrong1,wrong2],why_en:why_en,why_th:why_th,en:en,th:th,hint_en:hint_en,hint_th:hint_th});
  }
  // Form drills: assemble the left side, not just the English meaning.
  exercise('mf01','n3a05','time','form',
    'Use 開ける (open). Build the verb form immediately before とたんに.',
    'ใช้ 開ける (เปิด) เปลี่ยนเป็นรูปที่อยู่หน้า とたんに',
    '窓を＿＿とたんに、冷たい風が入ってきた。','まどを＿＿とたんに、つめたいかぜがはいってきた。',
    '開けた','開ける','開けて',
    'とたん attaches to the past form: 開ける → 開けた. 開ける is dictionary form; 開けて is te form. Neither builds this pattern.',
    'หน้า とたん ใช้รูปอดีต: 開ける → 開けた ส่วน 開ける เป็นรูปพจนานุกรม และ 開けて เป็นรูป て จึงต่อสำนวนนี้ไม่ได้',
    'The instant I opened the window, cold wind came in.','ทันทีที่เปิดหน้าต่าง ลมเย็นก็พัดเข้ามา',
    'Finish the first action: use Vた.','ทำเหตุการณ์แรกเสร็จแล้ว: ใช้ Vた');
  exercise('mf02','n2a03','time','form',
    'Use 終わる (finish). Build “as soon as the meeting ends”.',
    'ใช้ 終わる (จบ) สร้าง “ทันทีที่ประชุมจบ”',
    '会議が＿＿次第、ご連絡します。','かいぎが＿＿しだい、ごれんらくします。',
    '終わり','終わる','終わった',
    'For “as soon as”, 次第 takes the masu stem: 終わります → 終わり. Dictionary and past forms do not attach here.',
    '次第 ที่แปลว่า “ทันทีที่” ใช้รากรูป ます: 終わります → 終わり ไม่ใช้รูปพจนานุกรมหรืออดีต',
    'I will contact you as soon as the meeting ends.','จะติดต่อไปทันทีที่ประชุมจบ',
    'Start with 終わります, then remove ます.','เริ่มจาก 終わります แล้วตัด ます');
  exercise('mf03','n3a06','time','form',
    'Use する (do). You were right in the middle of cooking.',
    'ใช้ する (ทำ) ขณะนั้นกำลังทำอาหารอยู่พอดี',
    '料理を＿＿最中に、電話が鳴った。','りょうりを＿＿さいちゅうに、でんわがなった。',
    'している','した','する',
    'An activity in progress uses Vている + 最中に. した marks a completed action; する alone does not build the in-progress attachment.',
    'กิจกรรมที่กำลังทำใช้ Vている + 最中に ส่วน した บอกว่าทำแล้ว และ する อย่างเดียวไม่ใช่รูปเชื่อมของสำนวนนี้',
    'The phone rang while I was in the middle of cooking.','โทรศัพท์ดังขึ้นตอนกำลังทำอาหารอยู่พอดี',
    'Keep the action running: ている.','ให้กริยายังดำเนินอยู่: ている');
  exercise('mf04','n3a08','time','form',
    'Use する (do). Attach “only after” to 一人暮らしをする.',
    'ใช้ する (ทำ) ต่อ “หลังจากทำแล้วถึง…” กับ 一人暮らしをする',
    '一人暮らしを＿＿はじめて、家事の大変さがわかった。','ひとりぐらしを＿＿はじめて、かじのたいへんさがわかった。',
    'して','した','し',
    'てはじめて needs te form: する → して. した is past; し is a masu stem. This pattern connects an experience to a new realization.',
    'てはじめて ใช้รูป て: する → して ส่วน した เป็นอดีต และ し เป็นราก ます สำนวนนี้เชื่อมประสบการณ์กับความเข้าใจใหม่',
    'Only after living alone did I understand how demanding housework is.','พอได้อยู่คนเดียวถึงเข้าใจว่างานบ้านเหนื่อยแค่ไหน',
    'The pattern starts with て.','สำนวนนี้เริ่มด้วย て');
  exercise('mf05','n3a03','window','form',
    'Use 温かい (warm). Keep the soup warm in the first clause.',
    'ใช้ 温かい (อุ่น) บอกว่าซุปยังอุ่นอยู่',
    'スープが＿＿うちに、飲んでください。','スープが＿＿うちに、のんでください。',
    '温かい','温かく','温かいな',
    '温かい is an i-adjective, so keep い before うちに. 温かく is adverbial. Do not add な after an i-adjective.',
    '温かい เป็นคุณศัพท์ い จึงเก็บ い หน้า うちに ส่วน 温かく เป็นรูปขยายกริยา และไม่เติม な หลังคุณศัพท์ い',
    'Please drink the soup while it is still warm.','ดื่มซุปตอนที่ยังอุ่นอยู่นะ',
    'For the given i-adjective, keep its final い.','คุณศัพท์ い ที่กำหนดให้ต้องเก็บ い ไว้');
  exercise('mf06','n3a04','window','form',
    'Use the noun 夏休み (summer vacation). Attach it to 間.',
    'ใช้คำนาม 夏休み (ปิดเทอมฤดูร้อน) ต่อกับ 間',
    '＿＿間、ずっと祖母の家にいた。','＿＿あいだ、ずっとそぼのいえにいた。',
    '夏休みの','夏休みな','夏休みだ',
    'A noun links to 間 with の: 夏休みの間. な is not the noun connector here; だ would end a plain predicate instead.',
    'นามต่อ 間 ด้วย の: 夏休みの間 ไม่ใช้ な ส่วน だ ใช้จบภาคแสดงธรรมดา ไม่ใช่ตัวเชื่อมตรงนี้',
    'I stayed at my grandmother’s house throughout summer vacation.','อยู่บ้านคุณยายตลอดช่วงปิดเทอมฤดูร้อน',
    'Noun + の + time noun.','คำนาม + の + คำนามบอกเวลา');
  exercise('mf07','n2c13','obligation','form',
    'Use 変更する (change). Build the special する form for ざるを得ない.',
    'ใช้ 変更する (เปลี่ยน) สร้างรูปพิเศษของ する ใน ざるを得ない',
    '予算が足りず、計画を＿＿を得ない。','よさんがたりず、けいかくを＿＿をえない。',
    '変更せざる','変更しざる','変更するざる',
    'する is exceptional: せざるを得ない. Do not use the ordinary しない stem or dictionary する before ざる.',
    'する เป็นข้อยกเว้น ใช้ せざるを得ない ไม่ใช้ราก し จาก しない หรือรูปพจนานุกรม する หน้า ざる',
    'The budget is insufficient, so we have no choice but to change the plan.','งบไม่พอ จึงจำเป็นต้องเปลี่ยนแผน',
    'The irregular piece is せざる.','ส่วนพิเศษคือ せざる');
  exercise('mf08','n2c14','obligation','form',
    'Use 行く (go). You promised to attend, so you MUST go.',
    'ใช้ 行く (ไป) สัญญาว่าจะไปแล้ว จึงจำเป็นต้องไป',
    '出席すると約束したので、＿＿わけにはいかない。','しゅっせきするとやくそくしたので、＿＿わけにはいかない。',
    '行かない','行く','行き',
    'To mean “must go”, negate the action: 行かないわけにはいかない = cannot not go. 行くわけにはいかない reverses the meaning; 行き cannot attach.',
    'ถ้าหมายถึง “ต้องไป” ให้ปฏิเสธกริยา: 行かないわけにはいかない = ไม่ไปไม่ได้ ถ้าใช้ 行く จะกลายเป็นไปไม่ได้ และ 行き ต่อแบบนี้ไม่ได้',
    'I promised to attend, so I cannot skip it.','สัญญาว่าจะเข้าร่วมแล้ว จึงไม่ไปไม่ได้',
    '“Cannot NOT go” needs a negative verb first.','“ไม่ไปไม่ได้” ต้องเริ่มด้วยกริยาปฏิเสธ');
  exercise('mf09','n3b08','wake','form',
    'Use 忙しい (busy). A new fact explains why she is busy.',
    'ใช้ 忙しい (ยุ่ง) ข้อมูลใหม่อธิบายว่าทำไมเธอจึงยุ่ง',
    '仕事を二つしているんですね。だから、いつも＿＿わけですね。','しごとをふたつしているんですね。だから、いつも＿＿わけですね。',
    '忙しい','忙しく','忙しな',
    'Keep the plain i-adjective before わけ: 忙しいわけ. 忙しく is the adverbial form; 忙しな is not a valid form of 忙しい.',
    'เก็บคุณศัพท์ い รูปธรรมดาหน้า わけ: 忙しいわけ ส่วน 忙しく เป็นรูปขยายกริยา และ 忙しな ไม่ใช่รูปของคำนี้',
    'So you work two jobs. That explains why you are always busy.','ทำงานสองงานนี่เอง มิน่าถึงยุ่งตลอด',
    'i-adjective + わけ; no extra な or の.','คุณศัพท์ い + わけ ไม่ต้องเพิ่ม な หรือ の');
  exercise('mf10','n3b01','evidence','form',
    'Use 引っ越す (move house). You HEARD this information from a friend.',
    'ใช้ 引っ越す (ย้ายบ้าน) ข้อมูลนี้ได้ยินมาจากเพื่อน',
    '友達の話では、田中さんは来週＿＿そうです。','ともだちのはなしでは、たなかさんはらいしゅう＿＿そうです。',
    '引っ越す','引っ越し','引っ越して',
    'Reported そう keeps the plain clause: 引っ越すそうです. 引っ越しそう describes an impression/likelihood; 引っ越して does not attach to this そう.',
    'そう แบบบอกต่อเก็บอนุประโยคธรรมดา: 引っ越すそうです ถ้าใช้ 引っ越しそう จะเป็นการคาดจากสิ่งที่เห็น ส่วน 引っ越して ต่อ そう นี้ไม่ได้',
    'According to my friend, Tanaka is moving next week.','เพื่อนบอกว่าคุณทานากะจะย้ายบ้านสัปดาห์หน้า',
    'Reporting keeps the full plain verb.','การบอกต่อเก็บกริยารูปธรรมดาเต็มคำ');
  exercise('mf11','n3b02','evidence','form',
    'Use おいしい (delicious). You are looking at the cake, not reporting a review.',
    'ใช้ おいしい (อร่อย) คุณกำลังมองเค้ก ไม่ได้บอกต่อรีวิว',
    'このケーキは＿＿そうですね。','このケーキは＿＿そうですね。',
    'おいし','おいしい','おいしく',
    'For appearance, remove the final い: おいしい → おいしそう. おいしいそう means “I hear it is delicious”; おいしく cannot connect here.',
    'ถ้าบอกลักษณะที่เห็นให้ตัด い: おいしい → おいしそう แต่ おいしいそう คือ “ได้ยินว่าอร่อย” และ おいしく ใช้ต่อแบบนี้ไม่ได้',
    'This cake looks delicious.','เค้กนี้ดูน่าอร่อยนะ',
    'Appearance: i-adjective minus い + そう.','ลักษณะที่เห็น: คุณศัพท์ い ตัด い แล้วเติม そう');
  exercise('mf12','n3b03','evidence','form',
    'Use 静か (quiet), a na-adjective. Build an inference with ようだ.',
    'ใช้ 静か (เงียบ) ซึ่งเป็นคุณศัพท์ な สร้างข้อสันนิษฐานด้วย ようだ',
    '外から音が聞こえない。駅前はもう＿＿ようだ。','そとからおとがきこえない。えきまえはもう＿＿ようだ。',
    '静かな','静かの','静かだ',
    'A na-adjective uses な before ようだ. の is the noun connection, while だ belongs to a complete plain predicate.',
    'คุณศัพท์ な ใช้ な หน้า ようだ ส่วน の เป็นตัวเชื่อมคำนาม และ だ เป็นส่วนท้ายภาคแสดงธรรมดา',
    'I cannot hear any sound outside. The area in front of the station seems quiet now.','ไม่ได้ยินเสียงจากข้างนอกเลย แถวหน้าสถานีคงเงียบแล้ว',
    '静か is a na-adjective: restore な before よう.','静か เป็นคุณศัพท์ な จึงเติม な หน้า よう');
  exercise('mf13','n3a21','condition','form',
    'Use 着く (arrive). Build “when you have arrived”. The ら is already printed.',
    'ใช้ 着く (ถึง) สร้าง “เมื่อถึงแล้ว” ในประโยคมี ら ให้แล้ว',
    '家に＿＿ら、連絡してください。','いえに＿＿ら、れんらくしてください。',
    '着いた','着く','着いて',
    'たら is built from the past form + ら: 着く → 着いた → 着いたら. 着く and 着いて do not take this ら.',
    'たら สร้างจากรูปอดีต + ら: 着く → 着いた → 着いたら ส่วน 着く และ 着いて ต่อ ら แบบนี้ไม่ได้',
    'Please contact me when you get home.','ถึงบ้านแล้วติดต่อมาด้วยนะ',
    'く → いた, then add the given ら.','く → いた แล้วต่อกับ ら ที่มีให้');
  exercise('mf14','n2g11','condition','form',
    'Use 言う (say). Build the volitional warning pattern ～(よ)うものなら.',
    'ใช้ 言う (พูด) สร้างคำเตือน ～(よ)うものなら ด้วยรูปชักชวน',
    'そんな失礼なことを＿＿ものなら、相手を怒らせてしまう。','そんなしつれいなことを＿＿ものなら、あいてをおこらせてしまう。',
    '言おう','言う','言った',
    'The requested warning uses volitional + ものなら: 言う → 言おう. Dictionary 言う and past 言った do not make the specified ～(よ)うものなら pattern.',
    'คำเตือนที่โจทย์กำหนดใช้รูปชักชวน + ものなら: 言う → 言おう ส่วน 言う และ 言った ไม่ใช่รูปของ ～(よ)うものなら ที่ต้องการ',
    'If you were to say something that rude, you would make the other person angry.','ถ้าขืนพูดเสียมารยาทแบบนั้น อีกฝ่ายจะโกรธเอา',
    '言う → 言おう (volitional).','言う → 言おう (รูปชักชวน/ตั้งใจ)');
  exercise('mf15','n3a13','cause','form',
    'Use 雨 (rain), a noun. Connect it to せいで.',
    'ใช้คำนาม 雨 (ฝน) ต่อกับ せいで',
    '＿＿せいで、電車が遅れた。','＿＿せいで、でんしゃがおくれた。',
    '雨の','雨な','雨だ',
    'For this noun, use Nのせいで. な is used with na-adjectives; だ does not connect a noun to せいで.',
    'คำนามนี้ใช้ Nのせいで ส่วน な ใช้กับคุณศัพท์ な และ だ ไม่ได้เชื่อมนามกับ せいで',
    'The train was delayed because of the rain.','รถไฟล่าช้าเพราะฝนตก',
    'A noun takes の before せい.','คำนามใช้ の หน้า せい');
  exercise('mf16','n3a16','cause','form',
    'Use 新人 (a newcomer), a noun. Give a personal explanation with もので.',
    'ใช้คำนาม 新人 (คนใหม่) อธิบายเหตุผลส่วนตัวด้วย もので',
    'すみません。まだ新人＿＿もので、よくわからなくて。','すみません。まだしんじん＿＿もので、よくわからなくて。',
    'な','の','だ',
    'This is a useful exception to “noun + の”: Nなもので. の would be the wrong attachment here; だ is not retained before もので.',
    'สำนวนนี้ต้องจำต่างจาก “นาม + の”: ใช้ Nなもので ไม่ใช้ の และไม่เก็บ だ หน้า もので',
    'Sorry, I am still new, so I do not really understand yet.','ขอโทษนะ ยังเป็นคนใหม่อยู่เลยยังไม่ค่อยเข้าใจ',
    'Noun + なもので is a pattern worth learning as one piece.','จำ นาม + なもので เป็นชุดเดียว');
  exercise('mf17','n2a20','contrast','form',
    'Use 買う (buy) in the past. You bought it, but have not used it.',
    'ใช้ 買う (ซื้อ) รูปอดีต ซื้อแล้วแต่ยังไม่ได้ใช้',
    '新しい辞書を＿＿ものの、まだ一度も使っていない。','あたらしいじしょを＿＿ものの、まだいちどもつかっていない。',
    '買った','買い','買って',
    'The fact is completed, so use the plain past 買った before ものの. 買い is a stem; 買って is te form, not a plain clause.',
    'ซื้อไปแล้วจึงใช้รูปธรรมดาอดีต 買った หน้า ものの ส่วน 買い เป็นราก และ 買って เป็นรูป て ไม่ใช่อนุประโยคธรรมดา',
    'Although I bought a new dictionary, I have not used it even once.','ซื้อพจนานุกรมใหม่แล้ว แต่ยังไม่ได้ใช้สักครั้ง',
    '買う is a group 1 verb: う → った.','買う เป็นกลุ่ม 1: う → った');
  exercise('mf18','n2a25','contrast','form',
    'Use 簡単 (easy). Retain the plain predicate before からといって.',
    'ใช้ 簡単 (ง่าย) เก็บภาคแสดงรูปธรรมดาหน้า からといって',
    '簡単＿＿からといって、確認を省いてはいけない。','かんたん＿＿からといって、かくにんをはぶいてはいけない。',
    'だ','な','の',
    'からといって follows a plain clause: 簡単だ. な links a na-adjective to a noun-like expression; の is not used here.',
    'からといって ต่อจากอนุประโยคธรรมดา: 簡単だ ส่วน な ใช้ขยายนามหรือสำนวนแบบนาม และตรงนี้ไม่ใช้ の',
    'Just because it is easy, you must not skip checking it.','อย่าข้ามการตรวจสอบเพียงเพราะมันง่าย',
    'The plain sentence is 簡単だ.','ประโยคธรรมดาคือ 簡単だ');
  exercise('mf19','n2c21','mono_koto','form',
    'Use 作る (make). Give advice about what to do from now on.',
    'ใช้ 作る (สร้าง) ให้คำแนะนำว่าควรทำอะไรต่อจากนี้',
    '文法を使えるようになりたいなら、自分で例文を＿＿ことだ。','ぶんぽうをつかえるようになりたいなら、じぶんでれいぶんを＿＿ことだ。',
    '作る','作って','作った',
    'Advice ことだ uses dictionary form (or negative form for “do not”). 作った points to a past event; 作って cannot attach this way.',
    'ことだ แบบแนะนำใช้รูปพจนานุกรม (หรือรูปปฏิเสธเมื่อแนะว่าอย่าทำ) 作った เป็นอดีต และ 作って ต่อแบบนี้ไม่ได้',
    'If you want to be able to use grammar, you should make your own example sentences.','ถ้าอยากใช้ไวยากรณ์ได้ ควรลองแต่งประโยคตัวอย่างเอง',
    'Advice for an action: Vる + ことだ.','แนะนำให้ทำ: Vる + ことだ');
  exercise('mf20','n2d16','mono_koto','form',
    'Use 泳ぐ (swim). Recall a repeated childhood habit, not a general rule.',
    'ใช้ 泳ぐ (ว่ายน้ำ) รำลึกสิ่งที่เคยทำบ่อยในวัยเด็ก ไม่ใช่กฎทั่วไป',
    '子供のころ、夏にはよく川で＿＿ものだ。','こどものころ、なつにはよくかわで＿＿ものだ。',
    '泳いだ','泳ぐ','泳いで',
    'A recollection uses Vたものだ: 泳ぐ → 泳いだ. 泳ぐものだ suggests a general tendency; 泳いで cannot attach here.',
    'รำลึกอดีตใช้ Vたものだ: 泳ぐ → 泳いだ ถ้าใช้ 泳ぐものだ จะสื่อแนวโน้มทั่วไป และ 泳いで ต่อแบบนี้ไม่ได้',
    'When I was a child, I often used to swim in the river in summer.','ตอนเด็ก ๆ พอถึงหน้าร้อนก็เคยไปว่ายน้ำในแม่น้ำบ่อย ๆ',
    'For group 1 verbs ending in ぐ, past ends in いだ.','กริยากลุ่ม 1 ท้าย ぐ เปลี่ยนอดีตเป็น いだ');
  exercise('mf21','n2c07','change','form',
    'Use 回復する (recover). Describe a recovery in progress with つつある.',
    'ใช้ 回復する (ฟื้นตัว) บอกว่ากำลังฟื้นตัวด้วย つつある',
    '地域の観光業は回復＿＿つつある。','ちいきのかんこうぎょうはかいふく＿＿つつある。',
    'し','する','して',
    'つつある takes the masu stem: 回復します → 回復し. する is dictionary form and して is te form; neither attaches to つつある.',
    'つつある ใช้ราก ます: 回復します → 回復し ส่วน する เป็นรูปพจนานุกรม และ して เป็นรูป て จึงต่อไม่ได้',
    'The local tourism industry is gradually recovering.','ธุรกิจท่องเที่ยวในพื้นที่กำลังค่อย ๆ ฟื้นตัว',
    'Remove ます from 回復します.','ตัด ます ออกจาก 回復します');
  exercise('mf22','n3a11','attachment','form',
    'Use 行く (go). Build “every time I go to Tokyo”.',
    'ใช้ 行く (ไป) สร้าง “ทุกครั้งที่ไปโตเกียว”',
    '東京へ＿＿たびに、この店で食事をする。','とうきょうへ＿＿たびに、このみせでしょくじをする。',
    '行く','行った','行き',
    'たびに takes the dictionary verb: 行くたびに. Do not use the past form or masu stem for this attachment.',
    'たびに ใช้กริยารูปพจนานุกรม: 行くたびに ไม่ใช้รูปอดีตหรือราก ます สำหรับสูตรนี้',
    'Every time I go to Tokyo, I eat at this restaurant.','ทุกครั้งที่ไปโตเกียวจะกินข้าวที่ร้านนี้',
    'Repeated trigger: Vる + たびに.','เหตุการณ์ที่เกิดซ้ำ: Vる + たびに');
  exercise('mf23','n2b11','attachment','form',
    'Use 静か (quiet). Add a second advantage with 上に.',
    'ใช้ 静か (เงียบ) เพิ่มข้อดีอีกข้อด้วย 上に',
    'この部屋は＿＿上に、駅にも近い。','このへやは＿＿うえに、えきにもちかい。',
    '静かな','静かの','静か',
    'A na-adjective commonly takes な before 上に: 静かな上に. の is for certain noun attachments; the bare stem lacks the connector.',
    'คุณศัพท์ な มักใช้ な หน้า 上に: 静かな上に ส่วน の ใช้กับนามบางแบบ และ 静か เปล่า ๆ ขาดตัวเชื่อม',
    'This room is quiet, and it is also close to the station.','ห้องนี้เงียบ แถมยังใกล้สถานีด้วย',
    'Use the same な as 静かな部屋.','ใช้ な เหมือนใน 静かな部屋');
  exercise('mf24','n2g14','limits','form',
    'Use 調べる (check) in the past. Limit the claim to what you have checked.',
    'ใช้ 調べる (ตรวจสอบ) รูปอดีต จำกัดข้อสรุปตามข้อมูลที่ตรวจสอบแล้ว',
    '私が＿＿限りでは、この製品に問題はない。','わたしが＿＿かぎりでは、このせいひんにもんだいはない。',
    '調べた','調べ','調べて',
    'A completed investigation uses the plain past: 調べた限りでは. 調べ is a stem, and 調べて is te form; neither is a complete clause here.',
    'ตรวจสอบเสร็จแล้วใช้รูปธรรมดาอดีต: 調べた限りでは ส่วน 調べ เป็นราก และ 調べて เป็นรูป て ไม่เป็นอนุประโยคสมบูรณ์ตรงนี้',
    'As far as I have checked, there is no problem with this product.','เท่าที่ตรวจสอบมา ผลิตภัณฑ์นี้ไม่มีปัญหา',
    'The investigation is already complete: use Vた.','ตรวจสอบเสร็จแล้ว: ใช้ Vた');

  // Contrast drills: the scenario specifies the intended message.
  exercise('mc01','n3a05','time','contrast',
    'A sudden realization hit at the exact moment the train departed. Choose the immediate-event expression.',
    'นึกขึ้นได้ฉับพลันตอนรถไฟออกพอดี เลือกสำนวนเหตุการณ์ที่เกิดทันที',
    '電車が発車した＿＿、忘れ物に気づいた。','でんしゃがはっしゃした＿＿、わすれものにきづいた。',
    'とたんに','次第','最中に',
    'とたんに highlights the sudden moment after departure. 次第 would take 発車し and introduce a planned next action here; 最中に needs an activity still in progress.',
    'とたんに เน้นวินาทีที่เกิดเรื่องฉับพลันหลังรถไฟออก ส่วน 次第 ต้องใช้ 発車し และตรงนี้จะเป็นแผนทำขั้นต่อไป / 最中に ต้องเป็นกิจกรรมที่ยังดำเนินอยู่',
    'The instant the train departed, I realized I had forgotten something.','ทันทีที่รถไฟออก ก็นึกได้ว่าลืมของ',
    'A sudden event after Vた.','เหตุการณ์ฉับพลันหลัง Vた');
  exercise('mc02','n2a03','time','contrast',
    'An announcement promises to guide visitors as soon as preparations finish. It is a planned future step.',
    'ประกาศว่าจะพาผู้มาเยี่ยมเข้าทันทีที่เตรียมเสร็จ เป็นขั้นตอนที่วางแผนไว้',
    '受付の準備が＿＿、係員がご案内します。','うけつけのじゅんびが＿＿、かかりいんがごあんないします。',
    '終わり次第','終わったとたん','終わってはじめて',
    '終わり次第 fits a planned prompt response. とたん describes a sudden event rather than this service promise. てはじめて would emphasize that only then something becomes possible, not the promised immediacy.',
    '終わり次第 เหมาะกับขั้นตอนที่สัญญาว่าจะทำทันที とたん ใช้เล่าเหตุฉับพลัน ส่วน てはじめて จะเน้นว่าต้องหลังจากนั้นจึงทำได้ ไม่ได้เน้นคำสัญญาว่าจะทำทันที',
    'A staff member will guide you as soon as reception preparations are complete.','เจ้าหน้าที่จะพาเข้าทันทีที่เตรียมส่วนต้อนรับเสร็จ',
    'A formal “as soon as” promise uses a masu stem.','คำสัญญา “ทันทีที่” แบบทางการใช้ราก ます');
  exercise('mc03','n3a03','window','contrast',
    'You will leave Japan soon. You want to use the remaining opportunity to see sumo at least once.',
    'ใกล้จะออกจากญี่ปุ่นแล้ว อยากใช้โอกาสที่เหลือไปดูซูโม่สักครั้ง',
    '日本にいる＿＿、一度は相撲を見たい。','にほんにいる＿＿、いちどはすもうをみたい。',
    'うちに','間ずっと','たびに',
    'うちに marks the opportunity before your stay ends. 間ずっと means throughout the whole period, conflicting with a single visit. たびに means every time, not this remaining window.',
    'うちに บอกโอกาสก่อนการอยู่ญี่ปุ่นจะจบ 間ずっと หมายถึงตลอดช่วง ซึ่งไม่ตรงกับการไปดูครั้งหนึ่ง ส่วน たびに คือทุกครั้ง ไม่ใช่โอกาสที่เหลืออยู่ตอนนี้',
    'While I am still in Japan, I want to see sumo at least once.','ระหว่างที่ยังอยู่ญี่ปุ่น อยากดูซูโม่อย่างน้อยสักครั้ง',
    'Do it before this opportunity disappears.','ทำก่อนโอกาสนี้จะหมดไป');
  exercise('mc04','n3a02','window','contrast',
    'Three months have passed, but the speaker still considers their arrival recent.',
    'ผ่านมาสามเดือนแล้ว แต่ผู้พูดยังรู้สึกว่าเพิ่งมาได้ไม่นาน',
    '三か月前に日本に来た＿＿なので、まだ知らないことが多い。','さんかげつまえににほんにきた＿＿なので、まだしらないことがおおい。',
    'ばかり','ところ','最中',
    'ばかり allows “recent” from the speaker’s viewpoint. たところ normally points to the immediate just-finished stage; 最中 means in the middle and does not follow 来た here.',
    'ばかり ใช้เมื่อผู้พูดรู้สึกว่าเพิ่งเกิด ส่วน たところ มักเป็นช่วงทันทีหลังทำเสร็จ และ 最中 คือระหว่างกำลังทำ จึงไม่ใช้หลัง 来た ตรงนี้',
    'I only came to Japan three months ago, so there is still a lot I do not know.','เพิ่งมาญี่ปุ่นเมื่อสามเดือนก่อน จึงยังมีหลายอย่างที่ไม่รู้',
    '“Recent to me” can be longer than a few minutes.','“เพิ่ง” ในความรู้สึกผู้พูดอาจนานกว่าสองสามนาที');
  exercise('mc05','n3c06','obligation','contrast',
    'You could physically close the shop, but your responsibility means you CANNOT close it.',
    'ปิดร้านได้ในทางกายภาพ แต่หน้าที่ทำให้คุณปิดร้านไม่ได้',
    '今日は一人で店を任されている。勝手に店を＿＿。','きょうはひとりでみせをまかされている。かってにみせを＿＿。',
    '閉めるわけにはいかない','閉めないわけにはいかない','閉めることはない',
    '閉めるわけにはいかない means responsibility prevents closing. Adding ない before わけ reverses it to “must close”. ことはない says there is no need, not that duty prevents it.',
    '閉めるわけにはいかない คือหน้าที่ทำให้ปิดไม่ได้ ถ้าเพิ่ม ない หน้า わけ จะกลายเป็น “ต้องปิด” ส่วน ことはない คือไม่จำเป็น ไม่ใช่ทำไม่ได้เพราะหน้าที่',
    'I am in sole charge of the shop today. I cannot just close it on my own.','วันนี้ได้รับมอบหมายให้ดูร้านคนเดียว จะปิดร้านตามใจไม่ได้',
    'Cannot do = dictionary verb + わけにはいかない.','ทำไม่ได้ = กริยาพจนานุกรม + わけにはいかない');
  exercise('mc06','n2c14','obligation','contrast',
    'You hurt someone and feel an obligation to apologize: you MUST apologize.',
    'ทำให้อีกฝ่ายเสียใจ จึงรู้สึกว่ามีหน้าที่ต้องขอโทษ',
    '相手を傷つけてしまったのだから、＿＿。','あいてをきずつけてしまったのだから、＿＿。',
    '謝らないわけにはいかない','謝るわけにはいかない','謝ることはない',
    '謝らないわけにはいかない means you cannot avoid apologizing. 謝るわけにはいかない says you cannot apologize; 謝ることはない says no apology is needed.',
    '謝らないわけにはいかない คือไม่ขอโทษไม่ได้ ถ้า 謝るわけにはいかない คือขอโทษไม่ได้ และ 謝ることはない คือไม่จำเป็นต้องขอโทษ',
    'Since I have hurt the other person, I have to apologize.','ทำให้อีกฝ่ายเสียใจไปแล้ว จึงต้องขอโทษ',
    'The extra negative creates “cannot NOT do”.','คำปฏิเสธที่เพิ่มเข้ามาทำให้เป็น “ไม่ทำไม่ได้”');
  exercise('mc07','n3b09','wake','contrast',
    'Correct “everyone agrees” to “not everyone agrees”. Do not claim that unanimous agreement is impossible.',
    'แก้จาก “ทุกคนเห็นด้วย” เป็น “ไม่ได้เห็นด้วยกันทุกคน” ไม่ได้บอกว่าการเห็นด้วยพร้อมกันเป็นไปไม่ได้',
    '全員が賛成している＿＿。反対の人もいる。','ぜんいんがさんせいしている＿＿。はんたいのひともいる。',
    'わけではない','わけがない','わけだ',
    'わけではない corrects the overgeneralization. わけがない rejects the possibility strongly; わけだ affirms an explanatory conclusion. Those are different messages.',
    'わけではない แก้การเหมารวม ส่วน わけがない ปฏิเสธว่าเป็นไปไม่ได้อย่างหนักแน่น และ わけだ ยืนยันข้อสรุปเชิงเหตุผล จึงสื่อคนละอย่าง',
    'It is not that everyone agrees. Some people are opposed.','ไม่ได้เห็นด้วยกันทุกคน ยังมีคนคัดค้านอยู่',
    'Soften the overgeneralization: “not necessarily / not all”.','แก้การเหมารวมว่า “ไม่เสมอไป / ไม่ใช่ทั้งหมด”');
  exercise('mc08','n2d17','wake','contrast',
    'Reject the possibility strongly: “There is no way Tanaka is here now.”',
    'ปฏิเสธความเป็นไปได้อย่างหนักแน่นว่า “คุณทานากะไม่มีทางอยู่ที่นี่ตอนนี้”',
    '田中さんは今、海外にいる。今ここにいる＿＿。','たなかさんはいま、かいがいにいる。いまここにいる＿＿。',
    'わけがない','わけではない','わけだ',
    'わけがない expresses the intended strong impossibility. わけではない only denies a conclusion; わけだ would mean “that explains why Tanaka is here”, contradicting the premise.',
    'わけがない แสดงความเป็นไปไม่ได้ตามที่โจทย์ต้องการ ส่วน わけではない เพียงปฏิเสธข้อสรุป และ わけだ จะยืนยันว่าอยู่ที่นี่ซึ่งขัดกับข้อมูลก่อนหน้า',
    'Tanaka is abroad now. There is no way Tanaka is here at the moment.','ตอนนี้คุณทานากะอยู่ต่างประเทศ ไม่มีทางอยู่ที่นี่ตอนนี้',
    'Strong impossibility uses がない.','ความเป็นไปไม่ได้แบบหนักแน่นใช้ がない');
  exercise('mc09','n3b01','evidence','contrast',
    'You are passing on the weather forecast, not describing the sky yourself.',
    'คุณกำลังบอกต่อพยากรณ์อากาศ ไม่ได้คาดจากท้องฟ้าด้วยตัวเอง',
    '天気予報によると、明日は雨が＿＿。','てんきよほうによると、あしたはあめが＿＿。',
    '降るそうだ','降りそうだ','降ったそうだ',
    '降るそうだ reports a nonpast event. 降りそうだ gives an appearance-based prediction; 降ったそうだ reports past rain, which conflicts with 明日.',
    '降るそうだ บอกต่อเหตุการณ์ที่ยังไม่เกิด ส่วน 降りそうだ คือคาดจากสิ่งที่เห็น และ 降ったそうだ บอกว่าฝนตกไปแล้ว จึงขัดกับ 明日 (พรุ่งนี้)',
    'According to the weather forecast, it will rain tomorrow.','ตามพยากรณ์อากาศ พรุ่งนี้ฝนจะตก',
    'Heard/read information keeps the dictionary verb.','ข้อมูลที่ได้ยินหรืออ่านมาเก็บกริยาพจนานุกรม');
  exercise('mc10','n3b02','evidence','contrast',
    'No one told you anything. You look up at the dark clouds and predict rain.',
    'ไม่มีใครบอกข้อมูล คุณมองเมฆดำแล้วคาดว่าฝนจะตก',
    '空に黒い雲が広がっている。もうすぐ雨が＿＿。','そらにくろいくもがひろがっている。もうすぐあめが＿＿。',
    '降りそうだ','降るそうだ','降ったそうだ',
    '降りそうだ uses the masu stem to describe what appears likely. 降るそうだ and 降ったそうだ report information from elsewhere; the latter also makes it past.',
    '降りそうだ ใช้ราก ます บอกสิ่งที่ดูท่าจะเกิด ส่วน 降るそうだ และ 降ったそうだ เป็นข้อมูลที่ได้ยินมา โดยอย่างหลังเป็นอดีตด้วย',
    'Dark clouds are spreading across the sky. It looks as if it will rain soon.','เมฆดำกระจายเต็มฟ้า ดูท่าฝนจะตกเร็ว ๆ นี้',
    'See signs now: masu stem + そう.','เห็นสัญญาณตอนนี้: ราก ます + そう');
  exercise('mc11','n3a22','condition','contrast',
    'Your friend says they plan to go to Osaka. Give advice to follow BEFORE they leave.',
    'เพื่อนบอกว่ามีแผนไปโอซาก้า แนะนำให้ทำบางอย่างก่อนออกเดินทาง',
    '大阪に＿＿、出発前にこのアプリを入れておくと便利だよ。','おおさかに＿＿、しゅっぱつまえにこのアプリをいれておくとべんりだよ。',
    '行くなら','行ったら','行くと',
    'なら responds to the friend’s plan, so advice can come before departure. 行ったら places the next step after going; 行くと normally presents what follows going, not this premise-based advice.',
    'なら รับแผนของเพื่อนเป็นเงื่อนไข จึงแนะให้ทำก่อนเดินทางได้ 行ったら วางสิ่งถัดไปหลังไปแล้ว ส่วน 行くと มักบอกผลหลังไป ไม่ใช่คำแนะนำจากแผนที่เพิ่งพูดถึง',
    'If you are going to Osaka, it is useful to install this app before leaving.','ถ้าจะไปโอซาก้า ลงแอปนี้ไว้ก่อนออกเดินทางจะสะดวกนะ',
    'Responding to someone’s stated plan: なら.','รับเงื่อนไขจากแผนที่อีกฝ่ายบอก: なら');
  exercise('mc12','n3a21','condition','contrast',
    'Ask your friend to call you AFTER they have returned home. This is a one-time request.',
    'ขอให้เพื่อนโทรหาหลังกลับถึงบ้านแล้ว เป็นคำขอเฉพาะครั้งนี้',
    '家に＿＿、電話してください。','いえに＿＿、でんわしてください。',
    '帰ったら','帰ると','帰るなら',
    '帰ったら allows a request after the return is completed. 帰ると does not fit this one-time request. 帰るなら means “if you are going to go home”, changing the condition and timing.',
    '帰ったら ใช้ขอให้ทำหลังกลับถึงแล้วได้ 帰ると ไม่เหมาะกับคำขอเฉพาะครั้งนี้ และ 帰るなら คือ “ถ้าจะกลับบ้าน” ซึ่งเปลี่ยนเงื่อนไขและจังหวะเวลา',
    'Please call me when you get home.','กลับถึงบ้านแล้วโทรมาด้วยนะ',
    'First finish A, then please do B.','ทำ A เสร็จก่อน แล้วช่วยทำ B');
  exercise('mc13','n3a14','cause','contrast',
    'You sincerely thank your teacher for helping you pass. There is no sarcasm.',
    'ขอบคุณครูจากใจที่ช่วยให้ผ่าน ไม่ได้ประชด',
    '先生が練習を見てくれた＿＿、面接に合格できた。','せんせいがれんしゅうをみてくれた＿＿、めんせつにごうかくできた。',
    'おかげで','せいで','ばかりに',
    'おかげで credits the helpful cause. せいで blames a cause; ばかりに expresses regret about a bad result. Both conflict with the sincere gratitude specified here.',
    'おかげで ยกความดีให้สิ่งที่ช่วย せいで โทษสาเหตุ และ ばかりに เสียดายผลเสีย ทั้งสองจึงไม่ตรงกับความขอบคุณจริงใจที่โจทย์กำหนด',
    'Thanks to my teacher helping with practice, I passed the interview.','ผ่านสัมภาษณ์ได้เพราะครูช่วยดูการฝึกให้',
    'A helpful cause + a welcome result.','สาเหตุที่ช่วย + ผลที่ต้องการ');
  exercise('mc14','n2a14','cause','contrast',
    'Stress regret: a single small mistake caused an unfortunate consequence.',
    'เน้นความเสียดายที่ผิดเพียงนิดเดียวกลับทำให้เกิดผลเสีย',
    '名前を一文字間違えた＿＿、申し込みが無効になった。','なまえをひともじまちがえた＿＿、もうしこみがむこうになった。',
    'ばかりに','おかげで','上に',
    'ばかりに focuses on the regrettable result caused by that one mistake. おかげで normally credits a benefit. 上に adds another fact; it does not express the requested causal regret.',
    'ばかりに เน้นว่าเพียงความผิดพลาดนั้นทำให้เกิดผลน่าเสียดาย おかげで มักยกความดีให้ผลดี ส่วน 上に เพิ่มข้อมูลอีกข้อ ไม่ได้สื่อความเสียดายเชิงเหตุผลตามโจทย์',
    'Just because I got one character of my name wrong, my application became invalid.','แค่เขียนชื่อตัวเดียวผิด ใบสมัครก็กลายเป็นโมฆะ',
    '“All because of that one thing…” with regret.','“เพียงเพราะเรื่องนั้นเรื่องเดียว…” ด้วยความเสียดาย');
  exercise('mc15','n2a20','contrast','contrast',
    'Admit that you bought the camera, then contrast that with not using it yet.',
    'ยอมรับว่าซื้อกล้องแล้ว แล้วบอกสิ่งที่ขัดกันคือยังไม่ได้ใช้',
    'カメラを買った＿＿、忙しくてまだ使っていない。','カメラをかった＿＿、いそがしくてまだつかっていない。',
    'ものの','どころか','からには',
    'ものの keeps the purchase true while adding the disappointing contrast. どころか would overturn or intensify the first idea; からには would lead toward a commitment or expected consequence.',
    'ものの ยอมรับว่าซื้อจริงแล้วบอกสิ่งที่ไม่เป็นตามคาด どころか จะหักหรือขยายความคิดแรก ส่วน からには มักนำไปสู่หน้าที่ ความตั้งใจ หรือผลที่ควรตามมา',
    'Although I bought a camera, I have been too busy to use it yet.','ซื้อกล้องมาแล้ว แต่ยุ่งจนยังไม่ได้ใช้',
    'A is true, but the expected result did not follow.','A เป็นจริง แต่ผลที่คาดไว้ยังไม่ตามมา');
  exercise('mc16','n2c27','contrast','contrast',
    'You have an urgent deadline. Say that your circumstances leave no room for travel.',
    'มีเส้นตายด่วน ต้องการบอกว่าสถานการณ์นี้ไม่มีเวลาหรือกะจิตกะใจไปเที่ยว',
    '締め切りが今夜なので、旅行＿＿。','しめきりがこんやなので、りょこう＿＿。',
    'どころではない','どころか','ものの',
    'どころではない completes “I am in no position to travel”. どころか needs a further contrasting claim; ものの also needs a following clause and cannot complete this noun ending.',
    'どころではない จบความหมายว่า “สภาพนี้ไปเที่ยวไม่ได้” ส่วน どころか ต้องมีข้อความหักความคาดหมายต่อ และ ものの ก็ต้องมีอนุประโยคต่อ จบหลังนามแบบนี้ไม่ได้',
    'The deadline is tonight, so I am in no position to travel.','กำหนดส่งคืนนี้ จะเอาเวลาที่ไหนไปเที่ยว',
    'No room for it under these circumstances.','สถานการณ์ไม่อำนวยให้ทำสิ่งนั้น');
  exercise('mc17','n2d16','mono_koto','contrast',
    'Look back fondly on a habit you had years ago.',
    'นึกย้อนอย่างคิดถึงถึงสิ่งที่เคยทำเป็นประจำเมื่อหลายปีก่อน',
    '昔は毎晩、この公園を散歩した＿＿。','むかしはまいばん、このこうえんをさんぽした＿＿。',
    'ものだ','ことだ','わけがない',
    'Vたものだ expresses the recollection. Advice ことだ normally follows Vる/Vない, and does not express nostalgia. わけがない would deny that you walked there.',
    'Vたものだ ใช้รำลึกอดีต ส่วน ことだ แบบแนะนำมักต่อ Vる/Vない และไม่ได้สื่อความคิดถึง ขณะที่ わけがない จะปฏิเสธว่าไม่มีทางเคยเดินที่นั่น',
    'I used to take a walk in this park every evening.','เมื่อก่อนเคยมาเดินเล่นที่สวนนี้ทุกเย็นเลย',
    'Past habit + nostalgia: Vたものだ.','นิสัยในอดีต + ความรำลึก: Vたものだ');
  exercise('mc18','n2c22','mono_koto','contrast',
    'Reassure your friend: there is NO NEED to rush home. You are not forbidding it.',
    'บอกให้เพื่อนสบายใจว่าไม่จำเป็นต้องรีบกลับบ้าน ไม่ได้ห้ามกลับ',
    '雨はすぐにやむから、急いで帰る＿＿。','あめはすぐにやむから、いそいでかえる＿＿。',
    'ことはない','わけがない','ものではない',
    'ことはない means no necessity. わけがない says the action is impossible; ものではない gives a general warning that one should not do it. Neither matches reassurance about necessity.',
    'ことはない คือไม่จำเป็น わけがない คือไม่มีทางเป็นไปได้ และ ものではない เป็นคำเตือนทั่วไปว่าไม่ควรทำ จึงไม่ตรงกับการบอกว่าไม่ต้องรีบก็ได้',
    'The rain will stop soon, so there is no need to hurry home.','ฝนจะหยุดแล้ว ไม่ต้องรีบกลับบ้านก็ได้',
    'Unnecessary ≠ impossible or forbidden.','ไม่จำเป็น ≠ เป็นไปไม่ได้ หรือถูกห้าม');
  exercise('mc19','n2c07','change','contrast',
    'Give a factual report of a recovery currently progressing. Do not express advice or a deliberate habit.',
    'รายงานว่าการฟื้นตัวกำลังค่อย ๆ เกิดขึ้น ไม่ใช่ให้คำแนะนำหรือบอกนิสัยที่ตั้งใจทำ',
    '医師の説明では、病状は少しずつ＿＿。','いしのせつめいでは、びょうじょうはすこしずつ＿＿。',
    'よくなりつつある','よくなるべきだ','よくなるようにする',
    'つつある describes the change in progress. べきだ judges what should happen. ようにする describes a deliberate effort, not the observed course of the illness.',
    'つつある บอกการเปลี่ยนแปลงที่กำลังเกิด べきだ ตัดสินว่าสมควรเกิดอะไร และ ようにする บอกความพยายามโดยตั้งใจ ไม่ใช่รายงานอาการที่สังเกตได้',
    'According to the doctor, the condition is gradually improving.','แพทย์อธิบายว่าอาการกำลังค่อย ๆ ดีขึ้น',
    'A process in progress: stem + つつある.','กระบวนการที่กำลังเปลี่ยน: ราก ます + つつある');
  exercise('mc20','n3b12','change','contrast',
    'You deliberately make time to review each night. Emphasize your ongoing effort.',
    'คุณตั้งใจหาเวลาทบทวนทุกคืน เน้นว่าพยายามทำอย่างต่อเนื่อง',
    '忘れないように、毎晩五分は復習する＿＿。','わすれないように、まいばんごふんはふくしゅうする＿＿。',
    'ようにしている','ようになっている','一方だ',
    'ようにしている describes a conscious habit. ようになっている describes an established state or arrangement. 一方だ describes a continuing trend and is not the pattern for this deliberate daily routine.',
    'ようにしている บอกนิสัยที่ตั้งใจทำ ようになっている บอกสภาพหรือระบบที่เป็นเช่นนั้น และ 一方だ บอกแนวโน้มต่อเนื่อง ไม่ใช่กิจวัตรที่ตั้งใจทำทุกวันแบบนี้',
    'To avoid forgetting, I make a point of reviewing for at least five minutes every night.','พยายามทบทวนอย่างน้อยคืนละห้านาทีเพื่อไม่ให้ลืม',
    'I actively make sure to do it.','ฉันตั้งใจดูแลให้ตัวเองทำสิ่งนั้น');
  exercise('mc21','n3a09','attachment','contrast',
    'You opened the window and fell asleep without closing it. The open state remained.',
    'เปิดหน้าต่างแล้วหลับไปโดยไม่ได้ปิด สภาพเปิดยังคงอยู่',
    '窓を＿＿寝てしまった。','まどを＿＿ねてしまった。',
    '開けたまま','開けるために','開けるたびに',
    '開けたまま keeps the resulting open state. ために would make sleep a means of opening the window. たびに would mean you sleep every time you open it, a different repeated-event claim.',
    '開けたまま คงสภาพเปิดไว้ ために จะกลายเป็นนอนเพื่อเปิดหน้าต่าง และ たびに จะบอกว่าหลับทุกครั้งที่เปิด ซึ่งเป็นความหมายอีกแบบ',
    'I fell asleep with the window left open.','เผลอหลับไปทั้งที่ยังเปิดหน้าต่างอยู่',
    'An action completed, its state unchanged: Vたまま.','ทำกริยาแล้วและคงสภาพนั้นไว้: Vたまま');
  exercise('mc22','n3a11','attachment','contrast',
    'Say this happens EVERY time you go shopping. The point is recurrence, not doing an extra errand.',
    'บอกว่าเกิดขึ้นทุกครั้งที่ไปซื้อของ เน้นความเกิดซ้ำ ไม่ใช่การแวะทำอีกอย่าง',
    '買い物に行く＿＿、駅前の店でコーヒーを飲む。','かいものにいく＿＿、えきまえのみせでコーヒーをのむ。',
    'たびに','ついでに','ために',
    'たびに says “every time”. ついでに says you use one trip to do something else, without asserting every occurrence. ために would make drinking coffee the means or preparation for going shopping.',
    'たびに คือทุกครั้ง ついでに คือถือโอกาสทำอีกอย่างในทริปเดียวกัน โดยไม่ยืนยันว่าเกิดทุกครั้ง และ ために จะเป็นดื่มกาแฟเพื่อไปซื้อของ',
    'Every time I go shopping, I have coffee at the café in front of the station.','ทุกครั้งที่ไปซื้อของ จะดื่มกาแฟที่ร้านหน้าสถานี',
    'One trigger, the same result each time.','เหตุการณ์หนึ่งเกิด แล้วได้ผลแบบเดิมทุกครั้ง');
  exercise('mc23','n2b18','limits','contrast',
    'Expand the range: the shop opens not only on weekdays but on weekends too.',
    'ขยายขอบเขตว่าร้านเปิดทั้งวันธรรมดาและวันสุดสัปดาห์',
    'この店は平日＿＿、週末も営業している。','このみせはへいじつ＿＿、しゅうまつもえいぎょうしている。',
    'に限らず','に限って','の限りでは',
    'に限らず expands beyond weekdays, matching 週末も. に限って singles out a particular case; の限りでは does not build this “not only” relationship.',
    'に限らず ขยายจากวันธรรมดา จึงเข้ากับ 週末も ส่วน に限って เจาะจงกรณีหนึ่ง และ の限りでは ไม่ได้สร้างความสัมพันธ์ “ไม่จำกัดแค่” แบบนี้',
    'This shop is open not only on weekdays but on weekends too.','ร้านนี้ไม่ได้เปิดเฉพาะวันธรรมดา วันสุดสัปดาห์ก็เปิดด้วย',
    'Not limited to A; B also.','ไม่จำกัดแค่ A แต่ B ก็ด้วย');
  exercise('mc24','n2g14','limits','contrast',
    'Limit your statement to your present knowledge: there may be shops you do not know about.',
    'จำกัดข้อความตามความรู้ที่มีตอนนี้ อาจมีร้านที่คุณยังไม่รู้จักอีก',
    '私が知っている＿＿、この町にタイ料理店は二軒ある。','わたしがしっている＿＿、このまちにタイりょうりてんはにけんある。',
    '限りでは','うちに','に限って',
    '限りでは limits the claim to the evidence you have. うちに is about a time window or change during it; に限って singles out a noun and cannot follow 知っている here.',
    '限りでは จำกัดข้อสรุปตามข้อมูลที่มี うちに เกี่ยวกับช่วงเวลาหรือการเปลี่ยนแปลงระหว่างนั้น ส่วน に限って เจาะจงนาม จึงต่อ 知っている แบบนี้ไม่ได้',
    'As far as I know, there are two Thai restaurants in this town.','เท่าที่รู้ เมืองนี้มีร้านอาหารไทยสองร้าน',
    'Scope of evidence, not a time window.','ขอบเขตของหลักฐาน ไม่ใช่ช่วงเวลา');

  // Recall cards deliberately hide options until the learner asks to reveal.
  exercise('mr01','n2a03','time','recall',
    'Say the missing expression aloud before revealing. Promise: “I will let you know as soon as it is decided.”',
    'ลองพูดคำที่หายไปก่อนดูเฉลย สัญญาว่า “จะบอกทันทีที่ตัดสินใจได้”',
    '日程が決まり＿＿、お知らせします。','にっていがきまり＿＿、おしらせします。',
    '次第','とたん','うちに',
    '決まり is already the masu stem. 次第 adds the planned immediate response. とたん needs 決まった; うちに cannot attach to 決まり.',
    '決まり เป็นราก ます อยู่แล้ว 次第 จึงเติมความหมายว่าทำขั้นต่อไปทันที とたん ต้องใช้ 決まった และ うちに ต่อ 決まり ไม่ได้',
    'I will let you know as soon as the schedule is decided.','จะบอกให้ทราบทันทีที่กำหนดการแน่นอน',
    'Formal “as soon as”: two kanji, read しだい.','“ทันทีที่” แบบทางการ เป็นคันจิสองตัว อ่านว่า しだい');
  exercise('mr02','n3c06','obligation','recall',
    'Say the ending aloud: responsibility means “I cannot abandon it”.',
    'ลองพูดส่วนท้ายออกมา: เพราะความรับผิดชอบ “ฉันทิ้งงานนี้ไม่ได้”',
    '自分が引き受けた仕事だから、途中で投げ出す＿＿。','じぶんがひきうけたしごとだから、とちゅうでなげだす＿＿。',
    'わけにはいかない','ことはない','わけだ',
    'わけにはいかない expresses the responsibility preventing abandonment. ことはない only says abandonment is unnecessary; わけだ would explain that you do abandon it.',
    'わけにはいかない คือหน้าที่ทำให้ทิ้งงานไม่ได้ ことはない เพียงบอกว่าไม่จำเป็นต้องทิ้ง และ わけだ จะสรุปว่าทิ้งงานจริง',
    'I accepted this work myself, so I cannot abandon it halfway through.','รับงานนี้มาเอง จะทิ้งกลางคันไม่ได้',
    'Doing it would violate a responsibility: Vる + …','ถ้าทำจะผิดความรับผิดชอบ: Vる + …');
  exercise('mr03','n2a20','contrast','recall',
    'Recall the written “although” pattern: you registered, but have not started.',
    'นึกสำนวน “แม้ว่า” ที่มักใช้ในภาษาเขียน สมัครแล้วแต่ยังไม่เริ่ม',
    '講座に申し込んだ＿＿、まだ勉強を始めていない。','こうざにもうしこんだ＿＿、まだべんきょうをはじめていない。',
    'ものの','上に','からには',
    'ものの admits the registration and adds the contrasting lack of action. 上に adds a parallel point; からには points toward a commitment or expected consequence.',
    'ものの ยอมรับว่าสมัครแล้วแต่เพิ่มสิ่งที่ขัดกันคือยังไม่ลงมือ 上に เพิ่มข้อมูลทิศทางเดียวกัน ส่วน からには มักนำไปสู่หน้าที่หรือผลที่ควรเกิด',
    'Although I signed up for the course, I have not started studying yet.','สมัครคอร์สแล้ว แต่ยังไม่ได้เริ่มเรียนเลย',
    'The three-kana connector starts with も.','คำเชื่อมสามคานะขึ้นต้นด้วย も');
  exercise('mr04','n3a03','window','recall',
    'Recall “before I forget”, using the negative state that still holds now.',
    'นึกสำนวน “ก่อนที่จะลืม” โดยใช้สภาพปฏิเสธที่ยังเป็นจริงตอนนี้',
    '忘れない＿＿、メモしておこう。','わすれない＿＿、メモしておこう。',
    'うちに','たびに','次第',
    'ないうちに means before the action happens: while I have not forgotten yet. たびに would require a dictionary verb and recurring events; 次第 needs a masu stem for “as soon as”.',
    'ないうちに คือก่อนกริยานั้นเกิด ขณะที่ยังไม่ลืม たびに ต้องใช้รูปพจนานุกรมและบอกเหตุซ้ำ ส่วน 次第 ที่แปลว่าทันทีที่ต้องใช้ราก ます',
    'I will make a note before I forget.','จดไว้ก่อนที่จะลืมดีกว่า',
    'An opportunity that ends when I forget.','โอกาสที่หมดไปเมื่อลืม');
})();
